#version 450

struct Particle {
    vec2 position;
    vec2 velocity;
    vec4 color;
};

layout(std140, binding = 0) uniform ParameterUBO {
    float deltaTime;
} ubo;

layout(std430, binding = 1) readonly buffer ParticleSSBOIn {
    Particle particlesIn[];
};

layout(std430, binding = 2) buffer ParticleSSBOOut {
    Particle particlesOut[];
};

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

void main() {
    uint index = gl_GlobalInvocationID.x;
    Particle particle = particlesIn[index];
    particle.position += particle.velocity * ubo.deltaTime;

    if (particle.position.x <= -1.0 || particle.position.x >= 1.0) {
        particle.velocity.x = -particle.velocity.x;
    }
    if (particle.position.y <= -1.0 || particle.position.y >= 1.0) {
        particle.velocity.y = -particle.velocity.y;
    }

    particlesOut[index] = particle;
}
